"""Objective functions and objective-time static builders."""

from aind_low_point.optimization.objectives.coverage import (
    GaussianCoverageData,
    KdeCoverageData,
    coverage_ceiling_per_probe,
    coverage_per_probe_over_probes,
    coverage_total_over_probes,
    normalized_coverage_objective,
)
from aind_low_point.optimization.objectives.density import (
    DensityFn,
    coverage,
    gaussian_density,
    gaussian_mixture_density,
    integrate_density_along_shank,
    voxel_kde_density,
)
from aind_low_point.optimization.objectives.phase1 import (
    BrainSDFData,
    FixtureSDFData,
    Phase1Weights,
    make_phase1_objective,
    phase1_n_vars,
    phase1_to_full_x,
    phase1_unpack,
    reduced_to_phase1,
)
from aind_low_point.optimization.objectives.phase2 import Phase2Weights, make_phase2
from aind_low_point.optimization.objectives.probe_static import JointWeights
from aind_low_point.optimization.objectives.scalar import (
    ObjectiveBreakdown,
    ObjectiveWeights,
    OptimizerContext,
    ProbeContext,
    ProbeEvaluation,
    VariableLayout,
    evaluate_objective,
    evaluate_probe,
    headstage_capsule,
    kinematic_separations,
    make_objective,
    pairwise_headstage_clearances,
    scalar_objective,
)

__all__ = [
    "BrainSDFData",
    "DensityFn",
    "FixtureSDFData",
    "GaussianCoverageData",
    "JointWeights",
    "KdeCoverageData",
    "ObjectiveBreakdown",
    "ObjectiveWeights",
    "OptimizerContext",
    "Phase1Weights",
    "Phase2Weights",
    "ProbeContext",
    "ProbeEvaluation",
    "VariableLayout",
    "coverage",
    "coverage_ceiling_per_probe",
    "coverage_per_probe_over_probes",
    "coverage_total_over_probes",
    "evaluate_objective",
    "evaluate_probe",
    "gaussian_density",
    "gaussian_mixture_density",
    "headstage_capsule",
    "integrate_density_along_shank",
    "kinematic_separations",
    "make_objective",
    "make_phase1_objective",
    "make_phase2",
    "normalized_coverage_objective",
    "pairwise_headstage_clearances",
    "phase1_n_vars",
    "phase1_to_full_x",
    "phase1_unpack",
    "reduced_to_phase1",
    "scalar_objective",
    "voxel_kde_density",
]
