"""Configuration/dsl for low point.

The models are split by what they describe — leaf values, the catalog, the
scene, the plan — plus the template merge, canonicalization resolution and the
root model that validates across all of them. Importing from
``aind_rutter.config`` gets the whole public surface; a submodule is the place
to look when you want to know what owns a model.
"""

from aind_rutter.config.models_catalog import (
    EXTENSION_DEFAULTS,
    ROLE_PREFIX_DEFAULTS,
    AssetSpecModel,
    AssetSpecUnion,
    AssetTemplateModel,
    AtlasMeshPackSpecModel,
    BaseSpecModel,
    BaseTemplateModel,
    BulkAssetSpecModel,
    DerivedTargetSpecModel,
    RangeTargetSpecModel,
    TargetSpecModel,
    TargetSpecUnion,
    TargetTemplateModel,
)
from aind_rutter.config.models_common import (
    NO_RECORDING_ARRAY,
    RETIRED_FIELDS,
    UPGRADE_FROM_COMMIT,
    CanonicalizationDefModel,
    CanonicalizationOverrideModel,
    GeometrySourceModel,
    ImagingModel,
    IndexSelector,
    LabelSelector,
    LoadSITKTxOpModel,
    MaterialModel,
    NameSelector,
    PathSelector,
    PathsModel,
    RecordingModel,
    ResourceModel,
    RotateEulerTxOpModel,
    Selector,
    SourceSpace,
    TransformOp,
    TransformRecipeModel,
    TransformRefModel,
    TranslateTxOpModel,
    select_from_resource,
)
from aind_rutter.config.models_plan import (
    CalibrationRefModel,
    CalibrationReticleModel,
    CalibrationsModel,
    CalibrationSourceModel,
    CatalogTargetRefModel,
    HeadMountModel,
    InlineTargetRefModel,
    NodeTargetRefModel,
    PlanningModel,
    ProbeDeclModel,
    TargetRef,
)
from aind_rutter.config.models_scene import SceneModel, SceneNodeModel
from aind_rutter.config.root import ConfigModel, expand_config
from aind_rutter.config.templates import (
    apply_templates_generic,
    merge_asset_template_model_dumps,
    merge_target_template_model_dumps,
)

__all__ = [
    "EXTENSION_DEFAULTS",
    "NO_RECORDING_ARRAY",
    "RETIRED_FIELDS",
    "ROLE_PREFIX_DEFAULTS",
    "UPGRADE_FROM_COMMIT",
    "AssetSpecModel",
    "AssetSpecUnion",
    "AssetTemplateModel",
    "AtlasMeshPackSpecModel",
    "BaseSpecModel",
    "BaseTemplateModel",
    "BulkAssetSpecModel",
    "CalibrationRefModel",
    "CalibrationReticleModel",
    "CalibrationSourceModel",
    "CalibrationsModel",
    "CanonicalizationDefModel",
    "CanonicalizationOverrideModel",
    "CatalogTargetRefModel",
    "ConfigModel",
    "DerivedTargetSpecModel",
    "GeometrySourceModel",
    "HeadMountModel",
    "ImagingModel",
    "IndexSelector",
    "InlineTargetRefModel",
    "LabelSelector",
    "LoadSITKTxOpModel",
    "MaterialModel",
    "NameSelector",
    "NodeTargetRefModel",
    "PathSelector",
    "PathsModel",
    "PlanningModel",
    "ProbeDeclModel",
    "RangeTargetSpecModel",
    "RecordingModel",
    "ResourceModel",
    "RotateEulerTxOpModel",
    "SceneModel",
    "SceneNodeModel",
    "Selector",
    "SourceSpace",
    "TargetRef",
    "TargetSpecModel",
    "TargetSpecUnion",
    "TargetTemplateModel",
    "TransformOp",
    "TransformRecipeModel",
    "TransformRefModel",
    "TranslateTxOpModel",
    "apply_templates_generic",
    "expand_config",
    "merge_asset_template_model_dumps",
    "merge_target_template_model_dumps",
    "select_from_resource",
]
